export default {
  userInfo: '/api/v1/common/user/info',
  getCompleteCount: '/api/v1/user/testing/myexamcount',
  getTestExam: '/api/v1/user/testing/myexam',
  examExplain: '/api/v1/user/testing/exam_info',
  policy: '/api/v1/user/testing/signed/privacy/policy',
  policyAgreement: '/api/v1/user/testing/sign/privacy/policy',
  faceVerify: '/api/v1/user/testing/face/recognize',
  signature: '/api/v1/user/testing/sign/testing_sign',
  examPaper: '/api/v1/user/testing/user_paper',
  saveAnswer: '/api/v1/user/testing/save',
  examResult: '/api/v1/user/testing/exam_result',
  isSigned: '/api/v1/user/sign/exist',
  certificateRebuild: '/api/v1/user/testing/certificateImg/rebuild',
  recordList: '/api/v1/user/testing/exam_results/{examId}',
  examAnalysis: '/api/v1/user/testing/testing_record',
  ishaveRecords: '/api/v1/user/testing/exam/have/record',
  getPractiseNum: '/api/v1/user/testing/exam_paper_question_nums',
}